// Login action
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_RESET_MESSAGE = 'LOGIN_RESET_MESSAGE';

// Get user info from token
export const GET_USER_INFO_FROM_TOKEN = 'GET_USER_INFO_FROM_TOKEN';
export const GET_USER_INFO_FROM_TOKEN_SUCCESS = 'GET_USER_INFO_FROM_TOKEN_SUCCESS';
export const GET_USER_INFO_FROM_TOKEN_FAIL = 'GET_USER_INFO_FROM_TOKEN_FAIL';
export const GET_USER_INFO_FROM_TOKEN_RESET_MESSAGE = 'GET_USER_INFO_FROM_TOKEN_RESET_MESSAGE';

// Clear login data
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';

// Get genres
export const GET_ALL_GENRES = 'GET_ALL_GENRES';
export const GET_ALL_GENRES_SUCCESS = 'GET_ALL_GENRES_SUCCESS';
export const GET_ALL_GENRES_FAIL = 'GET_ALL_GENRES_FAIL';
export const GET_ALL_GENRES_RESET_MESSAGE = 'GET_ALL_GENRES_RESET_MESSAGE';

// Get authors by genreId
export const GET_AUTHORS_BY_GENRE_ID = 'GET_AUTHORS_BY_GENRE_ID';
export const GET_AUTHORS_BY_GENRE_ID_SUCCESS = 'GET_AUTHORS_BY_GENRE_ID_SUCCESS';
export const GET_AUTHORS_BY_GENRE_ID_FAIL = 'GET_AUTHORS_BY_GENRE_ID_FAIL';
export const GET_AUTHORS_BY_GENRE_ID_RESET_MESSAGE = 'GET_AUTHORS_BY_GENRE_ID_RESET_MESSAGE';

// Get books
export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL';
export const GET_BOOKS_RESET_MESSAGE = 'GET_BOOKS_RESET_MESSAGE';
export const GET_BOOKS_SAVE_DATA = 'GET_BOOKS_SAVE_DATA';
