// Login action
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_RESET_MESSAGE = 'LOGIN_RESET_MESSAGE';

// Get user info from token
export const GET_USER_INFO_FROM_TOKEN = 'GET_USER_INFO_FROM_TOKEN';
export const GET_USER_INFO_FROM_TOKEN_SUCCESS = 'GET_USER_INFO_FROM_TOKEN_SUCCESS';
export const GET_USER_INFO_FROM_TOKEN_FAIL = 'GET_USER_INFO_FROM_TOKEN_FAIL';
export const GET_USER_INFO_FROM_TOKEN_RESET_MESSAGE = 'GET_USER_INFO_FROM_TOKEN_RESET_MESSAGE';
