const ERROR_CODE = {
	LOGIN_ERROR: {
		UNKNOW: -1,
		WRONG_PASSWORD: 0,
		ACCOUNT_NOT_EXSIST: 1,
	},
	TOKEN_ERROR: {
		UNKNOW: -1,
		TOKEN_EXPIRED: 0,
		INVALID_TOKEN: 1,
		ACCOUNT_NOT_EXSIST: 2,
	},
	CREATE_ACCOUNT_ERROR: {
		UNKNOW: -1,
		ACCOUNT_EXSISTED: 0,
	},
	SEND_RESET_PASSWORD_ERROR: {
		UNKNOW: -1,
		ACCOUNT_NOT_EXSIST: 0,
	},
	VERIFY_PASSWORD_ERROR: {
		UNKNOW: -1,
		ACCOUNT_NOT_EXSIST: 0,
		TOKEN_EXPIRED: 1,
		INVALID_TOKEN: 2,
		WRONG_PASSWORD: 3,
	},
	RESET_PASSWORD_ERROR: {
		UNKNOW: -1,
		ACCOUNT_NOT_EXSIST: 0,
		WRONG_PASSWORD: 1,
	},
	GET_GENRES_ERROR: {
		UNKNOW: -1,
	},
	GET_AUTHOR_BY_GENRE_ERROR: {
		UNKNOW: -1,
		GENRE_NOT_FOUND: 0,
	},
	GET_AUTHOR_INFO_ERROR: {
		UNKNOW: -1,
		AUTHOR_NOT_EXSIST: 0,
	},
};

export default ERROR_CODE;