const dataProvince = [
	{id: 1, name: 'An Giang', checked: false, population: 1000},
	{id: 2, name: 'Bà Rịa - Vũng Tàu', checked: false, population: 400},
	{id: 3, name: 'Bắc Giang', checked: false, population: 252},
	{id: 4, name: 'Bắc Kạn', checked: false, population: 8500},
	{id: 5, name: 'Bạc Liêu', checked: false, population: 4623},
	{id: 6, name: 'Bắc Ninh', checked: false, population: 1022},
	{id: 7, name: 'Bến Tre', checked: false, population: 1024},
	{id: 8, name: 'Bình Định', checked: false, population: 7520},
	{id: 9, name: 'Bình Dương', checked: false, population: 253},
	{id: 10, name: 'Bình Phước', checked: false, population: 2566},
	{id: 11, name: 'Bình Thuận', checked: false, population: 2319},
	{id: 12, name: 'Cà Mau', checked: false, population: 2456},
	{id: 13, name: 'Cần Thơ', checked: false, population: 1024},
	{id: 14, name: 'Cao Bằng', checked: false, population: 2012},
	{id: 15, name: 'Đà Nẵng', checked: false, population: 3325},
	{id: 16, name: 'Đắk Lắk', checked: false, population: 351},
	{id: 17, name: 'Đắk Nông', checked: false, population: 1148},
	{id: 18, name: 'Điện Biên', checked: false, population: 911},
	{id: 19, name: 'Đồng Nai', checked: false, population: 3295},
	{id: 20, name: 'Đồng Tháp', checked: false, population: 3186},
	{id: 21, name: 'Gia Lai', checked: false, population: 1235},
	{id: 22, name: 'Hà Giang', checked: false, population: 2222},
	{id: 23, name: 'Hà Nam', checked: false, population: 7526},
	{id: 24, name: 'Hà Nội', checked: false, population: 3654},
	{id: 25, name: 'Hà Tĩnh', checked: false, population: 8752},
	{id: 26, name: 'Hải Dương', checked: false, population: 3563},
	{id: 27, name: 'Hải Phòng', checked: false, population: 352},
	{id: 28, name: 'Hậu Giang', checked: false, population: 3563},
	{id: 29, name: 'Hòa Bình', checked: false, population: 8855},
	{id: 30, name: 'Hưng Yên', checked: false, population: 5632},
	{id: 31, name: 'Khánh Hòa', checked: false, population: 9856},
	{id: 32, name: 'Kiên Giang', checked: false, population: 5252},
	{id: 33, name: 'Kon Tum', checked: false, population: 7852},
	{id: 34, name: 'Lai Châu', checked: false, population: 530},
	{id: 35, name: 'Lâm Đồng', checked: false, population: 25632},
	{id: 36, name: 'Lạng Sơn', checked: false, population: 25220},
	{id: 37, name: 'Lào Cai', checked: false, population: 582},
	{id: 38, name: 'Long An', checked: false, population: 5632},
	{id: 39, name: 'Nam Định', checked: false, population: 8552},
	{id: 40, name: 'Nghệ An', checked: false, population: 25230},
	{id: 41, name: 'Ninh Bình', checked: false, population: 5232},
	{id: 42, name: 'Ninh Thuận', checked: false, population: 5852},
	{id: 43, name: 'Phú Thọ', checked: false, population: 5214},
	{id: 44, name: 'Phú Yên', checked: false, population: 1012},
	{id: 45, name: 'Quảng Bình', checked: false, population: 2023},
	{id: 46, name: 'Quảng Nam', checked: false, population: 1048},
	{id: 47, name: 'Quảng Ngãi', checked: false, population: 7204},
	{id: 48, name: 'Quảng Ninh', checked: false, population: 1006},
	{id: 49, name: 'Quảng Trị', checked: false, population: 6253},
	{id: 50, name: 'Sóc Trăng', checked: false, population: 6325},
	{id: 51, name: 'Sơn La', checked: false, population: 4555},
	{id: 52, name: 'Tây Ninh', checked: false, population: 6666},
	{id: 53, name: 'Thái Bình', checked: false, population: 888},
	{id: 54, name: 'Thái Nguyên', checked: false, population: 7521},
	{id: 55, name: 'Thanh Hóa', checked: false, population: 356},
	{id: 56, name: 'Thừa Thiên Huế', checked: false, population: 653},
	{id: 57, name: 'Tiền Giang', checked: false, population: 3255},
	{id: 58, name: 'Thành phố Hồ Chí Minh', checked: false, population: 9852},
	{id: 59, name: 'Trà Vinh', checked: false, population: 26278},
	{id: 60, name: 'Tuyên Quang', checked: false, population: 5520},
	{id: 61, name: 'Vĩnh Long', checked: false, population: 6965},
	{id: 62, name: 'Vĩnh Phúc', checked: false, population: 4474},
	{id: 63, name: 'Yên Bái', checked: false, population: 5852},
];

export default dataProvince;